## Server
server:
  port: 8080

## Spring
spring:
  profiles:
    default: local

#  datasource:
#    url: jdbc:h2:mem:~/levelupApplication
##    url: jdbc:h2:tcp://localhost/~/Study/h2/db/levelup
#    username: sa
#    password: sa
#    driver-class-name: org.h2.Driver

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/levelup
    username: root
    password: 1234

# depend human error
  jpa:
    properties:
      hibernate:
        ddl-auto: none

# Logging
logging:
  level:
    org.hibernate.SQL: debug

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # v2.5~ Hibernate 초기화 이후 data.sql 실행

  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: never